apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hybiot-chart.fullname" . }}
  labels:
    {{- include "hybiot-chart.labels" . | nindent 4 }}
data:
    {{- .Values.configMapData | toYaml | nindent 2 }}

