{{ if  .Values.secretData -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hybiot-chart.fullname" . }}
  labels:
    {{- include "hybiot-chart.labels" . | nindent 4 }}
data:
{{- .Values.secretData | toYaml | nindent 2 }}
{{- end }}
